# Generated by Django 5.0.1 on 2024-01-24 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, default=None, null=True)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'events')},
                'index_together': {('user', 'events')},
            },
        ),
    ]
